# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Plane Django ORM app package.

Houses the persistence layer for the Plane API service: models, mixins, custom
managers/querysets, Django management commands, and the autogenerated migration
history. Assumes the ``migrator`` container has applied all migrations before
the API process begins serving requests.
"""
