/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

/**
 * Issue Gantt View Store — MobX view-layout cache for the issue Gantt chart.
 *
 * Owns the UI state that drives the Gantt visualization: the active timeline
 * granularity, the chart geometry payload for that granularity, the focused
 * block, and the rendered block list. The constructor takes no `rootStore`
 * argument (unusual versus the calendar and kanban view stores in this
 * directory) — this store is wired purely as a UI-state cache for the Gantt
 * chart layout and does not need access to the issue root store.
 *
 * State slice:
 *   - currentView: TGanttViews — active timeline granularity, default "month"
 *     (observable.ref).
 *   - currentViewData: ChartDataType | undefined — geometry and labels for the
 *     current view, generated by `currentViewDataWithView` (observable).
 *   - activeBlockId: string | null — id of the currently focused chart block
 *     (observable.ref).
 *   - renderView: derived block list passed to the chart renderer (observable);
 *     typed `any[]` on the class and declared as `any` on the interface — the
 *     payload shape is owned by the gantt-chart subsystem renderer.
 *
 * Actions (registered via `makeObservable` as `action.bound`):
 *   - updateCurrentView(view) — sets the timeline granularity; callers should
 *     follow up with a matching `updateCurrentViewData` payload.
 *   - updateCurrentViewData(data) — replaces the chart geometry payload.
 *   - updateActiveBlockId(blockId) — updates focus tracking for the chart.
 *   - updateRenderView(data) — replaces the rendered-blocks list.
 *   - initGantt() — internal initializer invoked from the constructor; seeds
 *     `currentViewData` for the default month view via `currentViewDataWithView`.
 *
 * Computed:
 *   - isBlockActive(blockId) — `computedFn` factory returning whether `blockId`
 *     matches `activeBlockId`. Memoized per id (distinct from a plain `computed`
 *     getter) so each call site gets a stable reactive subscription that
 *     recomputes only when `activeBlockId` changes.
 *
 * Consumers:
 *   - apps/web/core/components/issues/issue-layouts/gantt/** — Gantt chart
 *     layout components consume `currentView`, `currentViewData`,
 *     `activeBlockId`, and `renderView` for chart rendering and interactions.
 *   - Composed by apps/web/core/store/issue/root.store.ts (instantiated as part
 *     of the issue domain wiring; not surfaced under a dedicated hook in
 *     apps/web/core/hooks/store/).
 */

import { action, makeObservable, observable, runInAction } from "mobx";
import { computedFn } from "mobx-utils";
// helpers
import type { ChartDataType, TGanttViews } from "@plane/types";
import { currentViewDataWithView } from "@/components/gantt-chart/data";
// types

export interface IGanttStore {
  // observables
  currentView: TGanttViews;
  currentViewData: ChartDataType | undefined;
  activeBlockId: string | null;
  renderView: any;
  // computed functions
  isBlockActive: (blockId: string) => boolean;
  // actions
  updateCurrentView: (view: TGanttViews) => void;
  updateCurrentViewData: (data: ChartDataType | undefined) => void;
  updateActiveBlockId: (blockId: string | null) => void;
  updateRenderView: (data: any[]) => void;
}

export class GanttStore implements IGanttStore {
  // observables
  currentView: TGanttViews = "month";
  currentViewData: ChartDataType | undefined = undefined;
  activeBlockId: string | null = null;
  renderView: any[] = [];

  constructor() {
    makeObservable(this, {
      // observables
      currentView: observable.ref,
      currentViewData: observable,
      activeBlockId: observable.ref,
      renderView: observable,
      // actions
      updateCurrentView: action.bound,
      updateCurrentViewData: action.bound,
      updateActiveBlockId: action.bound,
      updateRenderView: action.bound,
    });

    this.initGantt();
  }

  /**
   * @description check if block is active
   * @param {string} blockId
   */
  isBlockActive = computedFn((blockId: string): boolean => this.activeBlockId === blockId);

  /**
   * @description update current view
   * @param {TGanttViews} view
   */
  updateCurrentView = (view: TGanttViews) => {
    this.currentView = view;
  };

  /**
   * @description update current view data
   * @param {ChartDataType | undefined} data
   */
  updateCurrentViewData = (data: ChartDataType | undefined) => {
    this.currentViewData = data;
  };

  /**
   * @description update active block
   * @param {string | null} block
   */
  updateActiveBlockId = (blockId: string | null) => {
    this.activeBlockId = blockId;
  };

  /**
   * @description update render view
   * @param {any[]} data
   */
  updateRenderView = (data: any[]) => {
    this.renderView = data;
  };

  /**
   * @description initialize gantt chart with month view
   */
  initGantt = () => {
    const newCurrentViewData = currentViewDataWithView(this.currentView);

    runInAction(() => {
      this.currentViewData = newCurrentViewData;
    });
  };
}
