/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

/**
 * Rich-text description editor for the issue modal, bridging React Hook Form and the internal TipTap wrapper.
 *
 * Rendered purpose: renders the `description_html` field via `RichTextEditor` (the first-party
 * `@/components/editor/rich-text` wrapper around `@plane/editor`), supporting asset upload, asset duplication
 * (for duplicate-work-item flows), workspace member mention search, Escape-to-close, an optional
 * "I'm feeling lucky" auto-generate button, and a `GptAssistantPopover` for inserting AI responses at the
 * cursor position. Renders a `Loader` skeleton until `descriptionHtmlData` resolves (i.e., until the initial
 * description backfill completes).
 *
 * Props (`TIssueDescriptionEditorProps`):
 *   - control (`Control<TIssue>`, required) — React Hook Form control bound to the parent issue form
 *   - isDraft (`boolean`, required) — selects between `EFileAssetType.DRAFT_ISSUE_DESCRIPTION` and
 *     `EFileAssetType.ISSUE_DESCRIPTION` when classifying uploads / duplicates
 *   - issueName (`string`, required) — passed to the GPT prompt for auto-generation; also gates the
 *     "I'm feeling lucky" button visibility (must be non-empty after trim)
 *   - issueId (`string | undefined`, required) — `entity_identifier` for asset uploads; empty string when
 *     creating a brand-new work item
 *   - descriptionHtmlData (`string | undefined`, required) — current resolved description HTML; `undefined`
 *     triggers the loader skeleton
 *   - editorRef (`React.MutableRefObject<EditorRefApi | null>`, required) — imperative handle into the editor
 *     used by the parent (`form.tsx` / `base.tsx`) for `clearEditor()`, `isEditorReadyToDiscard()`, and
 *     `setEditorValueAtCursorPosition(...)`
 *   - submitBtnRef (`React.MutableRefObject<HTMLButtonElement | null>`, required) — submit button ref; the
 *     editor's `onEnterKeyPress` calls `submitBtnRef.current?.click()`
 *   - gptAssistantModal (`boolean`, required) — controls `GptAssistantPopover.isOpen`
 *   - workspaceSlug (`string`, required) — used in workspace resolution, mention search, and AI requests
 *   - projectId (`string | null`, required) — used in upload / duplication / mention / GPT requests; when null,
 *     the editor renders the loader skeleton instead of the editor
 *   - handleFormChange (`() => void`, required) — invoked after every editor change to mark the parent form
 *     as dirty
 *   - handleDescriptionHTMLDataChange (`(descriptionHtmlData: string) => void`, required) — called once per
 *     `descriptionHtmlData` change to propagate the resolved HTML back to the parent state
 *   - setGptAssistantModal (`React.Dispatch<React.SetStateAction<boolean>>`, required) — controls the GPT
 *     popover open state
 *   - handleGptAssistantClose (`() => void`, required) — invoked when the popover closes; the parent uses this
 *     to avoid resetting the title after the popover closes
 *   - onAssetUpload (`(assetId: string) => void`, required) — called with each newly-uploaded or duplicated
 *     asset id so the parent can finalize them on submit (`FileService.updateBulkProjectAssetsUploadStatus`)
 *   - onClose (`() => void`, required) — Escape-key close callback (gated by `isEditorReadyToDiscard()`)
 *
 * MobX stores read (via hooks):
 *   - `useTranslation()` — `t` for i18n keys (placeholder, error messages)
 *   - `useWorkspace()` — `getWorkspaceBySlug` to resolve `workspaceId` (passed to the editor and the
 *     GPT popover)
 *   - `useInstance()` — `config` to gate AI features behind `config?.has_llm_configured`
 *   - `useEditorAsset()` — `uploadEditorAsset`, `duplicateEditorAsset` (asset persistence helpers)
 *   - `usePlatformOS()` — `isMobile` for `getTabIndex(ETabIndices.ISSUE_FORM, isMobile)`
 *
 * Service-layer interactions (direct calls, not via stores):
 *   - `aiService.createGptTask(workspaceSlug, { prompt, task })` — module-scoped `aiService` instance
 *     (`AIService`); invoked from `handleAutoGenerateDescription` ("I'm feeling lucky" button)
 *   - `workspaceService.searchEntity(workspaceSlug, { ...payload, project_id })` — module-scoped
 *     `workspaceService` instance (`WorkspaceService`); used as the editor's `searchMentionCallback` for @-mentions
 *
 * Side effects:
 *   - Asset upload: `uploadEditorAsset({ blockId, data: { entity_identifier, entity_type }, file, projectId,
 *     workspaceSlug })` — entity type is draft vs. live by `isDraft`. Calls `onAssetUpload(asset_id)` and
 *     returns the asset id to the editor for inline replacement.
 *   - Asset duplication: `duplicateEditorAsset({ assetId, entityId: issueId, entityType, projectId,
 *     workspaceSlug })` — used when the form was opened with `sourceIssueId` to clone assets into the new
 *     work item.
 *   - AI auto-generation: `aiService.createGptTask` — on success, inserts the returned HTML at the cursor via
 *     `editorRef.current?.setEditorValueAtCursorPosition(response)`. Surfaces error toasts for HTTP 429
 *     (rate limit, 50/month/user) and other failures.
 *   - Mention search: workspace entity search (members) for the @-mention picker inside the editor.
 *   - Toasts: `setToast({ type: TOAST_TYPE.ERROR, title: "Error!", message: ... })` for editor-not-ready-to-discard,
 *     empty-AI-response, and GPT errors.
 *   - Keyboard: `useKeypress("Escape", handleKeyDown)` — Escape triggers `onClose()` only when the editor is
 *     ready to discard; otherwise an error toast is shown and the default action is prevented.
 *
 * Derived state / imperative notes:
 *   - The `descriptionHtmlData` synchronization effect fires
 *     `handleDescriptionHTMLDataChange(descriptionHtmlData)` whenever `descriptionHtmlData` updates. The
 *     existing `// eslint-disable-next-line react-hooks/exhaustive-deps` comment is intentional (avoids
 *     re-running on `handleDescriptionHTMLDataChange` reference change) — preserve it verbatim.
 *   - The `iAmFeelingLucky` local state toggles the AI button's disabled / "cursor-wait" / "Generating
 *     response" copy.
 *   - The `Loader` skeleton renders when `descriptionHtmlData === undefined` OR `!projectId` — both
 *     conditions must resolve before the editor mounts (prevents asset uploads / mention search from firing
 *     against a null project).
 *   - `submitBtnRef?.current?.click()` is the wiring for Enter-to-submit from the editor surface — preserve
 *     the `onEnterKeyPress` prop verbatim.
 *
 * Architectural notes (per AAP §0.2.2):
 *   - MobX exclusively for state.
 *   - `@plane/editor` is the internal TipTap wrapper — treat `EditorRefApi` and `RichTextEditor` as
 *     first-party APIs, not as third-party abstractions.
 *   - Service layer: `AIService` and `WorkspaceService` are instantiated at module scope (typical pattern
 *     for stateless service classes in this codebase) — DO NOT move these into the component body.
 *   - i18n via `@plane/i18n` `useTranslation()`; some user-facing strings (the toast titles "Error!" and the
 *     "I'm feeling lucky" / "Generating response" copy and the AI error message strings) are hard-coded —
 *     these are pre-existing strings; DO NOT translate them as part of this documentation work.
 */

import React, { useEffect, useState } from "react";
import { observer } from "mobx-react";
import type { Control } from "react-hook-form";
import { Controller } from "react-hook-form";
import { Sparkle } from "lucide-react";
// plane imports
import { ETabIndices } from "@plane/constants";
import type { EditorRefApi } from "@plane/editor";
import { useTranslation } from "@plane/i18n";
import { TOAST_TYPE, setToast } from "@plane/propel/toast";
import type { TIssue } from "@plane/types";
import { EFileAssetType } from "@plane/types";
import { Loader } from "@plane/ui";
import { getDescriptionPlaceholderI18n, getTabIndex } from "@plane/utils";
// components
import { GptAssistantPopover } from "@/components/core/modals/gpt-assistant-popover";
import { RichTextEditor } from "@/components/editor/rich-text";
// helpers
// hooks
import { useEditorAsset } from "@/hooks/store/use-editor-asset";
import { useInstance } from "@/hooks/store/use-instance";
import { useWorkspace } from "@/hooks/store/use-workspace";
import useKeypress from "@/hooks/use-keypress";
import { usePlatformOS } from "@/hooks/use-platform-os";
// plane web services
import { WorkspaceService } from "@/services/workspace.service";
// services
import { AIService } from "@/services/ai.service";
const workspaceService = new WorkspaceService();
const aiService = new AIService();

type TIssueDescriptionEditorProps = {
  control: Control<TIssue>;
  isDraft: boolean;
  issueName: string;
  issueId: string | undefined;
  descriptionHtmlData: string | undefined;
  editorRef: React.MutableRefObject<EditorRefApi | null>;
  submitBtnRef: React.MutableRefObject<HTMLButtonElement | null>;
  gptAssistantModal: boolean;
  workspaceSlug: string;
  projectId: string | null;
  handleFormChange: () => void;
  handleDescriptionHTMLDataChange: (descriptionHtmlData: string) => void;
  setGptAssistantModal: React.Dispatch<React.SetStateAction<boolean>>;
  handleGptAssistantClose: () => void;
  onAssetUpload: (assetId: string) => void;
  onClose: () => void;
};

export const IssueDescriptionEditor = observer(function IssueDescriptionEditor(props: TIssueDescriptionEditorProps) {
  const {
    control,
    isDraft,
    issueName,
    issueId,
    descriptionHtmlData,
    editorRef,
    submitBtnRef,
    gptAssistantModal,
    workspaceSlug,
    projectId,
    handleFormChange,
    handleDescriptionHTMLDataChange,
    setGptAssistantModal,
    handleGptAssistantClose,
    onAssetUpload,
    onClose,
  } = props;
  // i18n
  const { t } = useTranslation();
  // states
  const [iAmFeelingLucky, setIAmFeelingLucky] = useState(false);
  // store hooks
  const { getWorkspaceBySlug } = useWorkspace();
  const workspaceId = getWorkspaceBySlug(workspaceSlug?.toString())?.id ?? "";
  const { config } = useInstance();
  const { uploadEditorAsset, duplicateEditorAsset } = useEditorAsset();
  // platform
  const { isMobile } = usePlatformOS();

  const { getIndex } = getTabIndex(ETabIndices.ISSUE_FORM, isMobile);

  useEffect(() => {
    if (descriptionHtmlData) handleDescriptionHTMLDataChange(descriptionHtmlData);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [descriptionHtmlData]);

  const handleKeyDown = (event: KeyboardEvent) => {
    if (editorRef.current?.isEditorReadyToDiscard()) {
      onClose();
    } else {
      setToast({
        type: TOAST_TYPE.ERROR,
        title: "Error!",
        message: "Editor is still processing changes. Please wait before proceeding.",
      });
      event.preventDefault(); // Prevent default action if editor is not ready to discard
    }
  };

  useKeypress("Escape", handleKeyDown);

  // handlers
  const handleAiAssistance = async (response: string) => {
    if (!workspaceSlug || !projectId) return;

    editorRef.current?.setEditorValueAtCursorPosition(response);
  };

  const handleAutoGenerateDescription = async () => {
    if (!workspaceSlug || !projectId) return;

    setIAmFeelingLucky(true);

    aiService
      .createGptTask(workspaceSlug.toString(), {
        prompt: issueName,
        task: "Generate a proper description for this work item.",
      })
      .then((res) => {
        if (res.response === "")
          setToast({
            type: TOAST_TYPE.ERROR,
            title: "Error!",
            message:
              "Work item title isn't informative enough to generate the description. Please try with a different title.",
          });
        else handleAiAssistance(res.response_html);
      })
      .catch((err) => {
        const error = err?.data?.error;

        if (err.status === 429)
          setToast({
            type: TOAST_TYPE.ERROR,
            title: "Error!",
            message: error || "You have reached the maximum number of requests of 50 requests per month per user.",
          });
        else
          setToast({
            type: TOAST_TYPE.ERROR,
            title: "Error!",
            message: error || "Some error occurred. Please try again.",
          });
      })
      .finally(() => setIAmFeelingLucky(false));
  };

  return (
    <div className="relative rounded-lg border-[0.5px] border-subtle-1 bg-layer-2">
      {descriptionHtmlData === undefined || !projectId ? (
        <Loader className="max-h-64 min-h-[120px] space-y-2 overflow-hidden rounded-md border border-subtle p-3 py-2 pt-3">
          <Loader.Item width="100%" height="26px" />
          <div className="flex items-center gap-2">
            <Loader.Item width="26px" height="26px" />
            <Loader.Item width="400px" height="26px" />
          </div>
          <div className="flex items-center gap-2">
            <Loader.Item width="26px" height="26px" />
            <Loader.Item width="400px" height="26px" />
          </div>
          <Loader.Item width="80%" height="26px" />
          <div className="flex items-center gap-2">
            <Loader.Item width="50%" height="26px" />
          </div>
          <div className="border-0.5 absolute right-3.5 bottom-2 z-10 flex items-center gap-2">
            <Loader.Item width="100px" height="26px" />
            <Loader.Item width="50px" height="26px" />
          </div>
        </Loader>
      ) : (
        <>
          <Controller
            name="description_html"
            control={control}
            render={({ field: { value, onChange } }) => (
              <RichTextEditor
                editable
                id="issue-modal-editor"
                initialValue={value ?? ""}
                value={descriptionHtmlData}
                workspaceSlug={workspaceSlug?.toString()}
                workspaceId={workspaceId}
                projectId={projectId}
                onChange={(_description: object, description_html: string) => {
                  onChange(description_html);
                  handleFormChange();
                }}
                onEnterKeyPress={() => submitBtnRef?.current?.click()}
                ref={editorRef}
                tabIndex={getIndex("description_html")}
                placeholder={(isFocused, description) => t(getDescriptionPlaceholderI18n(isFocused, description))}
                searchMentionCallback={async (payload) =>
                  await workspaceService.searchEntity(workspaceSlug?.toString() ?? "", {
                    ...payload,
                    project_id: projectId?.toString() ?? "",
                  })
                }
                containerClassName="pt-3 min-h-[120px]"
                uploadFile={async (blockId, file) => {
                  try {
                    const { asset_id } = await uploadEditorAsset({
                      blockId,
                      data: {
                        entity_identifier: issueId ?? "",
                        entity_type: isDraft
                          ? EFileAssetType.DRAFT_ISSUE_DESCRIPTION
                          : EFileAssetType.ISSUE_DESCRIPTION,
                      },
                      file,
                      projectId,
                      workspaceSlug,
                    });
                    onAssetUpload(asset_id);
                    return asset_id;
                  } catch (error) {
                    console.log("Error in uploading issue asset:", error);
                    throw new Error("Asset upload failed. Please try again later.");
                  }
                }}
                duplicateFile={async (assetId: string) => {
                  try {
                    const { asset_id } = await duplicateEditorAsset({
                      assetId,
                      entityId: issueId,
                      entityType: isDraft ? EFileAssetType.DRAFT_ISSUE_DESCRIPTION : EFileAssetType.ISSUE_DESCRIPTION,
                      projectId,
                      workspaceSlug,
                    });
                    onAssetUpload(asset_id);
                    return asset_id;
                  } catch {
                    throw new Error("Asset duplication failed. Please try again later.");
                  }
                }}
              />
            )}
          />
          <div className="border-0.5 z-10 flex items-center justify-end gap-2 p-3">
            {issueName && issueName.trim() !== "" && config?.has_llm_configured && (
              <button
                type="button"
                className={`flex items-center gap-1 rounded-sm bg-surface-2 px-1.5 py-1 text-caption-sm-regular hover:bg-layer-1 ${
                  iAmFeelingLucky ? "cursor-wait" : ""
                }`}
                onClick={handleAutoGenerateDescription}
                disabled={iAmFeelingLucky}
                tabIndex={getIndex("feeling_lucky")}
              >
                {iAmFeelingLucky ? (
                  "Generating response"
                ) : (
                  <>
                    <Sparkle className="h-3.5 w-3.5" />I{"'"}m feeling lucky
                  </>
                )}
              </button>
            )}
            {config?.has_llm_configured && projectId && (
              <GptAssistantPopover
                isOpen={gptAssistantModal}
                handleClose={() => {
                  setGptAssistantModal((prevData) => !prevData);
                  // this is done so that the title do not reset after gpt popover closed
                  handleGptAssistantClose();
                }}
                onResponse={(response) => {
                  handleAiAssistance(response);
                }}
                placement="top-end"
                button={
                  <button
                    type="button"
                    className="flex items-center gap-1 rounded-sm bg-surface-2 px-1.5 py-1 text-caption-sm-regular hover:bg-layer-1"
                    onClick={() => setGptAssistantModal((prevData) => !prevData)}
                    tabIndex={-1}
                  >
                    <Sparkle className="h-4 w-4" />
                    AI
                  </button>
                }
                workspaceId={workspaceId}
                workspaceSlug={workspaceSlug}
                projectId={projectId}
              />
            )}
          </div>
        </>
      )}
    </div>
  );
});
